### PR TITLE
More flexible color fade from dark to light

### PR DESCRIPTION
**Pull request by Jamedjo**
Fades opacity between film ratings of 4 and 7.8. Also adjusts a:link HSL
color to darken high ratings.

### CODE REVIEW

**Comment by ovidiuch** [comment]
Hi, can you please revert the line endings into UNIX type? Beside not wanting Windows line endings, I can't even look at the diffs properly because it just marks all lines as changed. Thanks!

**Comment by Jamedjo** [comment]
Oops, my bad. Didn't even notice, forgot to set `git config --global core.autocrlf false` on new pc.

Should be fixed now, but had to make 'duplicate' commits.

**Comment by ovidiuch** [comment]
@Jamedjo, I am terribly sorry for ignoring your pull request for an year now. The color transitions are dope. You changes caused an issue where unknown types are now shown with default color, whereas before they were faded to the max (mostly future films with ratings N/A)

I will merge your pull, apply the quick fix myself and mention you

Thanks for contributing!

**Comment by ovidiuch** [comment]
Done, you can see #2 for the additional changes. I updated the Chrome Extension and bumped its version to 1.2. You can see it here https://chrome.google.com/webstore/detail/imdb-ratings/fbbcaooelpdopodjcneapidogdpelfeg (I even updated the screenshots to show your dope colors)

Thanks again for your contribution and sorry for the delay!

PS. The extension has 276 active users and I didn't advertise it in any way. Not much but still something :)

**Pull request merged**
